# Generated by Django 4.2.16 on 2024-09-16 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aerogeneradores', '0003_aerogenerador_uuid_ultimo_estado'),
        ('estadoAerogeneradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoaerogenerador',
            name='uuid_aerogenerador',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='aerogeneradores.aerogenerador'),
            preserve_default=False,
        ),
    ]
