# Generated by Django 4.2.16 on 2024-09-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadoAerogeneradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoaerogenerador',
            name='estado_final_clasificacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
