# Generated by Django 4.2.16 on 2024-12-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadoAerogeneradores', '0003_remove_estadoaerogenerador_progreso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoaerogenerador',
            options={'verbose_name': 'Estado Aerogenerador', 'verbose_name_plural': 'Estados Aerogeneradores'},
        ),
    ]
