# Generated by Django 4.2.16 on 2024-09-14 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parquesEolicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('id_parque_eolico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parquesEolicos.parqueeolico')),
            ],
        ),
    ]
