# Generated by Django 4.2.16 on 2024-09-14 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_parque_eolico',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='uuid_cliente',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
