# Generated by Django 4.2.16 on 2024-09-14 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0003_remove_cliente_id_cliente_and_more'),
        ('parquesEolicos', '0002_parqueseolicos_delete_parqueeolico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='uuid_parque_eolico',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, to='parquesEolicos.parqueseolicos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='uuid_usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
