# Generated by Django 4.2.16 on 2024-09-14 20:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estadoAerogeneradores', '0001_initial'),
        ('aerogeneradores', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteAerogenerador',
            fields=[
                ('uuid_componente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_componente', models.CharField(max_length=255)),
                ('coordenada_longitud', models.FloatField()),
                ('coordenada_latitud', models.FloatField()),
                ('ruta_imagen_visualizacion_componente', models.CharField(max_length=255)),
                ('uuid_aerogenerador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerogeneradores.aerogenerador')),
                ('uuid_ultimo_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estadoAerogeneradores.estadoaerogenerador')),
            ],
        ),
    ]
