# Generated by Django 4.2.16 on 2024-09-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0001_initial'),
        ('componentesAerogenerador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenteaerogenerador',
            name='uuid_inspeccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inspecciones.inspeccion'),
            preserve_default=False,
        ),
    ]
