# Generated by Django 4.2.16 on 2024-09-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentesAerogenerador', '0002_componenteaerogenerador_uuid_inspeccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componenteaerogenerador',
            name='uuid_inspeccion',
        ),
    ]
