# Generated by Django 4.2.16 on 2024-10-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentesAerogenerador', '0003_remove_componenteaerogenerador_uuid_inspeccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componenteaerogenerador',
            name='coordenada_latitud',
        ),
        migrations.RemoveField(
            model_name='componenteaerogenerador',
            name='coordenada_longitud',
        ),
        migrations.RemoveField(
            model_name='componenteaerogenerador',
            name='uuid_ultimo_estado',
        ),
    ]
