# Generated by Django 4.2.16 on 2024-11-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentesAerogenerador', '0004_remove_componenteaerogenerador_coordenada_latitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componenteaerogenerador',
            name='ruta_imagen_visualizacion_componente',
        ),
        migrations.AlterField(
            model_name='componenteaerogenerador',
            name='tipo_componente',
            field=models.CharField(choices=[('helice_a', 'Hélice A'), ('helice_b', 'Hélice B'), ('helice_c', 'Hélice C'), ('torre', 'Torre'), ('nacelle', 'Nacelle/Hub')], max_length=50),
        ),
    ]
