# Generated by Django 4.2.16 on 2024-12-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentesAerogenerador', '0006_alter_componenteaerogenerador_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componenteaerogenerador',
            options={'verbose_name': 'Componente Aerogenerador', 'verbose_name_plural': 'Componentes Aerogeneradores'},
        ),
    ]
