# Generated by Django 4.2.16 on 2024-09-14 20:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imagenes', '0001_initial'),
        ('anomalias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenAnomalia',
            fields=[
                ('uuid_imagen_anomalia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid_anomalia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anomalias.anomalia')),
                ('uuid_imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagenes.imagen')),
            ],
        ),
    ]
