# Generated by Django 4.2.16 on 2024-12-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagenesAnomalias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenanomalia',
            options={'verbose_name': 'Imagen Anomalía', 'verbose_name_plural': 'Imagenes Anomalías'},
        ),
    ]
