# Generated by Django 4.2.16 on 2024-09-17 16:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parquesEolicos', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('uuid_empresa', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('uuid_parque_eolico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parquesEolicos.parqueseolicos')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
