# Generated by Django 4.2.16 on 2024-09-17 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_delete_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='uuid_parque_eolico',
        ),
    ]
