# Generated by Django 4.2.16 on 2024-12-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_remove_empresa_uuid_parque_eolico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
