# Generated by Django 4.2.16 on 2024-09-16 22:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspecciones', '0001_initial'),
        ('componentesAerogenerador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoComponente',
            fields=[
                ('uuid_estado', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado_final_clasificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('progreso', models.CharField(max_length=255)),
                ('uuid_componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componentesAerogenerador.componenteaerogenerador')),
                ('uuid_inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspecciones.inspeccion')),
            ],
        ),
    ]
