# Generated by Django 4.2.16 on 2024-09-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParqueEolico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parque', models.CharField(max_length=255)),
                ('ubicacion_comuna', models.CharField(max_length=255)),
                ('ubicacion_region', models.CharField(max_length=255)),
                ('cantidad_turbinas', models.IntegerField()),
                ('potencia_instalada', models.FloatField()),
                ('coordenada_longitud', models.FloatField()),
                ('coordenada_latitud', models.FloatField()),
            ],
        ),
    ]
