# Generated by Django 4.2.16 on 2024-09-16 22:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParquesEolicos',
            fields=[
                ('uuid_parque', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_parque', models.CharField(max_length=255)),
                ('ubicacion_comuna', models.CharField(max_length=255)),
                ('ubicacion_region', models.CharField(max_length=255)),
                ('cantidad_turbinas', models.IntegerField()),
                ('potencia_instalada', models.FloatField()),
                ('coordenada_longitud', models.FloatField()),
                ('coordenada_latitud', models.FloatField()),
            ],
        ),
    ]
