# Generated by Django 4.2.16 on 2024-09-14 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cliente_id_cliente_and_more'),
        ('parquesEolicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParquesEolicos',
            fields=[
                ('uuid_parque', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_parque', models.CharField(max_length=255)),
                ('ubicacion_comuna', models.CharField(max_length=255)),
                ('ubicacion_region', models.CharField(max_length=255)),
                ('cantidad_turbinas', models.IntegerField()),
                ('potencia_instalada', models.FloatField()),
                ('coordenada_longitud', models.FloatField()),
                ('coordenada_latitud', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='ParqueEolico',
        ),
    ]
