# Generated by Django 4.2.16 on 2024-09-17 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_remove_empresa_uuid_parque_eolico'),
        ('parquesEolicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parqueseolicos',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parques', to='empresas.empresa'),
            preserve_default=False,
        ),
    ]
