# Generated by Django 4.2.16 on 2024-09-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parquesEolicos', '0002_parqueseolicos_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parqueseolicos',
            old_name='empresa',
            new_name='uuid_empresa',
        ),
    ]
