# Generated by Django 4.2.16 on 2024-09-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parquesEolicos', '0003_rename_empresa_parqueseolicos_uuid_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parqueseolicos',
            old_name='uuid_parque',
            new_name='uuid_parque_eolico',
        ),
    ]
