# Generated by Django 4.2.16 on 2024-10-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parquesEolicos', '0004_rename_uuid_parque_parqueseolicos_uuid_parque_eolico'),
    ]

    operations = [
        migrations.AddField(
            model_name='parqueseolicos',
            name='abreviatura_parque',
            field=models.CharField(default='emp', max_length=255),
            preserve_default=False,
        ),
    ]
