# Generated by Django 4.2.16 on 2024-12-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parquesEolicos', '0005_parqueseolicos_abreviatura_parque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parqueseolicos',
            options={'verbose_name': 'Parque Eólico', 'verbose_name_plural': 'Parques Eólicos'},
        ),
    ]
