# Generated by Django 4.2.16 on 2024-09-16 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('componentesAerogenerador', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspecciones', '__first__'),
        ('aerogeneradores', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalia',
            fields=[
                ('uuid_anomalia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_anomalia', models.CharField(max_length=100)),
                ('severidad_anomalia', models.IntegerField(choices=[(1, 'Sin daño'), (2, 'Menor'), (3, 'Significativo'), (4, 'Mayor'), (5, 'Crítico')])),
                ('dimension_anomalia', models.CharField(max_length=255)),
                ('orientacion_anomalia', models.CharField(max_length=255)),
                ('descripcion_anomalia', models.TextField(blank=True, null=True)),
                ('observacion_anomalia', models.TextField(blank=True, null=True)),
                ('coordenada_x', models.FloatField()),
                ('coordenada_y', models.FloatField()),
                ('uuid_aerogenerador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerogeneradores.aerogenerador')),
                ('uuid_componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componentesAerogenerador.componenteaerogenerador')),
                ('uuid_inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspecciones.inspeccion')),
                ('uuid_tecnico', models.ForeignKey(db_column='uuid_tecnico_clasificador', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anomalía',
                'verbose_name_plural': 'Anomalías',
            },
        ),
    ]
