# Generated by Django 4.2.16 on 2024-09-14 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspecciones', '0001_initial'),
        ('componentesAerogenerador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anomalias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalia',
            name='uuid_componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componentesAerogenerador.componenteaerogenerador'),
        ),
        migrations.AddField(
            model_name='anomalia',
            name='uuid_inspeccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspecciones.inspeccion'),
        ),
        migrations.AddField(
            model_name='anomalia',
            name='uuid_tecnico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
