# Generated by Django 4.2.16 on 2024-10-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalias', '0002_alter_anomalia_uuid_tecnico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomalia',
            name='coordenada_x',
        ),
        migrations.RemoveField(
            model_name='anomalia',
            name='coordenada_y',
        ),
        migrations.AlterField(
            model_name='anomalia',
            name='descripcion_anomalia',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
