# Generated by Django 4.2.16 on 2024-12-02 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anomalias', '0004_remove_anomalia_observacion_anomalia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomalia',
            name='ubicacion_componente',
        ),
    ]
