# Generated by Django 4.2.16 on 2024-09-16 21:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parquesEolicos', '__first__'),
        ('estadoAerogeneradores', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerogenerador',
            fields=[
                ('uuid_aerogenerador', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_aerogenerador', models.IntegerField()),
                ('modelo_aerogenerador', models.CharField(max_length=255)),
                ('fabricante_aerogenerador', models.CharField(max_length=255)),
                ('altura_aerogenerador', models.FloatField()),
                ('diametro_rotor', models.FloatField()),
                ('potencia_nominal', models.FloatField()),
                ('coordenada_longitud', models.FloatField()),
                ('coordenada_latitud', models.FloatField()),
                ('uuid_parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parquesEolicos.parqueseolicos')),
                ('uuid_ultimo_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estadoAerogeneradores.estadoaerogenerador')),
            ],
        ),
    ]
