# Generated by Django 4.2.16 on 2024-09-14 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerogenerador',
            fields=[
                ('uuid_aerogenerador', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_aerogenerador', models.IntegerField()),
                ('modelo_aerogenerador', models.CharField(max_length=255)),
                ('fabricante_aerogenerador', models.CharField(max_length=255)),
                ('altura_aerogenerador', models.FloatField()),
                ('diametro_rotor', models.FloatField()),
                ('potencia_nominal', models.FloatField()),
                ('coordenada_longitud', models.FloatField()),
                ('coordenada_latitud', models.FloatField()),
            ],
        ),
    ]
