# Generated by Django 4.2.16 on 2024-09-14 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estadoAerogeneradores', '0001_initial'),
        ('aerogeneradores', '0001_initial'),
        ('parquesEolicos', '0002_parqueseolicos_delete_parqueeolico'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerogenerador',
            name='uuid_parque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parquesEolicos.parqueseolicos'),
        ),
        migrations.AddField(
            model_name='aerogenerador',
            name='uuid_ultimo_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estadoAerogeneradores.estadoaerogenerador'),
        ),
    ]
