# Generated by Django 4.2.16 on 2024-09-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerogeneradores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aerogenerador',
            name='uuid_ultimo_estado',
        ),
    ]
