# Generated by Django 4.2.16 on 2024-09-15 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estadoAerogeneradores', '0001_initial'),
        ('aerogeneradores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerogenerador',
            name='uuid_ultimo_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estadoAerogeneradores.estadoaerogenerador'),
        ),
    ]
