# Generated by Django 4.2.16 on 2024-09-16 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estadoAerogeneradores', '__first__'),
        ('aerogeneradores', '0002_remove_aerogenerador_uuid_ultimo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerogenerador',
            name='uuid_ultimo_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estadoAerogeneradores.estadoaerogenerador'),
        ),
    ]
