# Generated by Django 4.2.16 on 2024-09-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerogeneradores', '0003_aerogenerador_uuid_ultimo_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aerogenerador',
            old_name='uuid_parque',
            new_name='uuid_parque_eolico',
        ),
        migrations.RemoveField(
            model_name='aerogenerador',
            name='uuid_ultimo_estado',
        ),
    ]
