# Generated by Django 4.2.16 on 2024-12-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerogeneradores', '0004_rename_uuid_parque_aerogenerador_uuid_parque_eolico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aerogenerador',
            options={'verbose_name': 'Aerogenerador', 'verbose_name_plural': 'Aerogeneradores'},
        ),
    ]
