# Generated by Django 4.2.16 on 2024-09-14 20:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspecciones', '0001_initial'),
        ('componentesAerogenerador', '0001_initial'),
        ('aerogeneradores', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('uuid_imagen', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_imagen', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField()),
                ('ruta_imagen', models.CharField(max_length=255)),
                ('estado_clasificacion', models.CharField(max_length=255)),
                ('uuid_aerogenerador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerogeneradores.aerogenerador')),
                ('uuid_componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componentesAerogenerador.componenteaerogenerador')),
                ('uuid_inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspecciones.inspeccion')),
            ],
        ),
    ]
