# Generated by Django 4.2.16 on 2024-09-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='estado_clasificacion',
            field=models.CharField(choices=[('clasificada', 'Clasificada'), ('no_clasificada', 'No Clasificada')], default='no_clasificada', max_length=255),
        ),
    ]
