# Generated by Django 4.2.16 on 2024-09-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='estado_clasificacion',
            field=models.CharField(choices=[('no_clasificada', 'No Clasificada'), ('con_dano', 'Con Daño'), ('sin_dano', 'Sin Daño')], default='no_clasificada', max_length=255),
        ),
    ]
