# Generated by Django 4.2.16 on 2024-12-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0003_alter_imagen_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='estado_clasificacion',
        ),
    ]
