# Generated by Django 4.2.16 on 2024-09-14 20:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parquesEolicos', '0002_parqueseolicos_delete_parqueeolico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('uuid_inspeccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inspeccion', models.DateField()),
                ('fecha_siguiente_inspeccion', models.DateField(blank=True, null=True)),
                ('progreso', models.CharField(max_length=255)),
                ('uuid_parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parquesEolicos.parqueseolicos')),
            ],
        ),
    ]
