# Generated by Django 4.2.16 on 2024-09-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspeccion',
            old_name='uuid_parque',
            new_name='uuid_parque_eolico',
        ),
    ]
