# Generated by Django 4.2.16 on 2024-11-23 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parquesEolicos', '0005_parqueseolicos_abreviatura_parque'),
        ('inspecciones', '0002_rename_uuid_parque_inspeccion_uuid_parque_eolico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='uuid_parque_eolico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='parquesEolicos.parqueseolicos'),
        ),
    ]
