# Generated by Django 4.2.16 on 2024-11-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0004_alter_inspeccion_uuid_parque_eolico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='progreso',
            field=models.IntegerField(choices=[(1, 'Completado'), (0, 'No Completado')], default=0),
        ),
    ]
