# Generated by Django 4.2.16 on 2024-12-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0005_alter_inspeccion_progreso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspeccion',
            options={'verbose_name': 'Inspección', 'verbose_name_plural': 'Inspecciones'},
        ),
    ]
